# Generated by Django 6.0 on 2025-12-25 21:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConfig',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=100, verbose_name='Action Name')),
                ('xp_value', models.IntegerField(verbose_name='XP Value')),
            ],
            options={
                'verbose_name': 'Action Rule',
                'verbose_name_plural': 'Action Rules',
                'db_table': 'ACTION_CONFIG',
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Allergen Name')),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
                'db_table': 'ALLERGEN',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_date', models.DateField(unique=True, verbose_name='Menu Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Daily Menu',
                'verbose_name_plural': 'Daily Menus',
                'db_table': 'DAILY_MENU',
                'ordering': ['-menu_date'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Meal Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'db_table': 'MEAL',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_name', models.CharField(max_length=50, unique=True, verbose_name='Rank Name')),
                ('min_xp', models.IntegerField(verbose_name='Minimum XP')),
                ('icon_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'db_table': 'RANK',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Total XP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rank', verbose_name='Rank')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('xp_gained', models.IntegerField(verbose_name='XP Gained')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actionconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'db_table': 'ACTION_LOG',
            },
        ),
        migrations.CreateModel(
            name='MealNutrition',
            fields=[
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.meal')),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.IntegerField(blank=True, null=True)),
                ('carbs', models.IntegerField(blank=True, null=True)),
                ('fat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meal Nutrition Info',
                'verbose_name_plural': 'Meal Nutrition Info',
                'db_table': 'MEAL_NUTRITION',
            },
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dailymenu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
            ],
            options={
                'verbose_name': 'Item Rating',
                'verbose_name_plural': 'Item Ratings',
                'db_table': 'ITEM_RATING',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('upvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('downvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dailymenu')),
                ('subject_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Comment',
                'verbose_name_plural': 'User Comments',
                'db_table': 'USER_COMMENT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealAllergen',
            fields=[
                ('pk', models.CompositePrimaryKey('meal_id', 'allergen_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allergen')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
            ],
            options={
                'verbose_name': 'Meal-Allergen Link',
                'verbose_name_plural': 'Meal-Allergen Links',
                'db_table': 'MEAL_ALLERGEN',
                'unique_together': {('meal', 'allergen')},
            },
        ),
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('pk', models.CompositePrimaryKey('menu_id', 'meal_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailymenu')),
            ],
            options={
                'verbose_name': 'Menu Content',
                'verbose_name_plural': 'Menu Contents',
                'db_table': 'MENU_CONTENT',
                'unique_together': {('menu', 'meal')},
            },
        ),
    ]
