# Generated by Django 6.0 on 2025-12-27 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], default='UP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.usercomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Vote',
                'verbose_name_plural': 'Comment Votes',
                'db_table': 'COMMENT_VOTE',
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
