# Generated by Django 6.0 on 2025-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
    ]
