# Generated by Django 6.0 on 2025-12-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rank_level'),
    ]

    operations = [
    ]
